### ISSUE TITLE
Unnecessary loading screen

### ISSUE THREAD

**Issue by carlos-dubon** [Angel-Ponce/Dynamic-Schedule#1]
When the app is first launched a JProgressBar is showed to the user. This just ruins the UX.

```
for (int i = 1; i <= 100; i++) {
    progress.setValue(i);
    Process.sleep(7);
}
```

https://github.com/Angel-Ponce/Dynamic-Schedule/blob/main/Schedule/src/ScheduleStructure/Controller.java

This for loop just makes the app seem unoptimized. A small .json file should load asap, but the progress bar makes it seem its a slow process.

**Comment by carlos-dubon** [comment]
pls fix, it has been 3 months now

**Comment by Angel-Ponce** [comment]
You can go to `store/Schedule.jar` to download the latest version
